version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies for GUI
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pytest
      - run:
          name: Run tests with virtual display
          command: |
            Xvfb :99 -ac &
            export DISPLAY=:99
            . venv/bin/activate
            pytest

workflows:
  version: 2
  test:
    jobs:
      - test
