version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      # Checkout the code
      - checkout

      # Install dependencies and virtual display setup
      - run:
          name: Install dependencies and Xvfb
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      # Start virtual display
      - run:
          name: Start Xvfb
          command: |
            Xvfb :99 -screen 0 1024x768x16 &
            export DISPLAY=:99

      # Run the tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest test_notes_app.py

workflows:
  version: 2
  test-workflow:
    jobs:
      - test