version: 2.1

jobs:
  test:
    docker:
      # Use an official Python Docker image
      - image: circleci/python:3.9
    steps:
      # Checkout the code
      - checkout

      # Set up Python environment
      - run:
          name: Install Python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      # Run the tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest test_notes_app.py

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
      